# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
