# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160508_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_photo',
            field=models.ImageField(upload_to='/products'),
        ),
    ]
