# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160508_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_photo',
            field=models.ImageField(upload_to='/featured_photos'),
        ),
    ]
