# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20160522_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
