# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20160522_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
