# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20160523_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_photo',
            field=models.ImageField(blank=True, null=True, upload_to='featured_photos'),
        ),
    ]
